# Generated by Django 4.2.7 on 2023-11-05 15:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="Email",
        ),
    ]
