# Generated by Django 4.2.7 on 2023-11-04 19:20

import Products.models
import Warehouse.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Products", "0001_initial"),
        ("Users", "0001_initial"),
        ("Main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("RC", models.CharField(max_length=24, verbose_name="کد سفارش")),
                ("slug", models.SlugField(default=uuid.uuid4, max_length=500)),
                (
                    "TotalPrice",
                    models.IntegerField(default=0, verbose_name="مبلغ کل سبد خرید"),
                ),
                (
                    "Amount",
                    models.IntegerField(default=0, verbose_name="مبلغ کل سفارشات"),
                ),
                (
                    "TotalDiscount",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="مجموع تخفیف"
                    ),
                ),
                (
                    "Tax",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="مالیات بر ارزش افزوده",
                    ),
                ),
                (
                    "ShippingPrice",
                    models.IntegerField(default=0, verbose_name="هزینه ارسال"),
                ),
                ("ShippingPriceAdded", models.BooleanField(default=False)),
                (
                    "UserBankAccountNumber",
                    models.CharField(
                        default="0", max_length=50, verbose_name="شماره حساب تراکنش"
                    ),
                ),
                (
                    "PaymentWay",
                    models.IntegerField(
                        choices=[(1, "Bank"), (2, "Zarinpal")],
                        default=1,
                        verbose_name="روش پرداخت",
                    ),
                ),
                (
                    "PaymentTransactionNumber",
                    models.CharField(
                        default="0", max_length=50, verbose_name="شماره تراکنش بانکی"
                    ),
                ),
                (
                    "PaymentDate",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="تاریخ پرداخت",
                    ),
                ),
                (
                    "PurchaseTrackNumber",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="کد پیگیری"
                    ),
                ),
                (
                    "policyAccept",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="تایید شرایط و قوانین",
                    ),
                ),
                ("weight", models.IntegerField(default=0, verbose_name="وزن کل")),
                ("Created", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Created"),
                            (1, "Inproccess"),
                            (2, "Discarded"),
                            (3, "Posted"),
                            (4, "Exchangerequest"),
                            (5, "Exchanged"),
                        ],
                        default=0,
                        verbose_name="وضعیت سبد خرید",
                    ),
                ),
                (
                    "Barcode",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Warehouse.models.PurchaseFiles,
                        verbose_name="تصویر بارکد",
                    ),
                ),
                ("Vouchered", models.BooleanField(default=False, verbose_name="کوپن")),
                (
                    "VoucherCode",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="کد کوپن"
                    ),
                ),
                ("Active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "HasReturn",
                    models.BooleanField(default=False, verbose_name="مورد مرجوعی"),
                ),
                (
                    "HasCancel",
                    models.BooleanField(default=False, verbose_name="مورد لغو شده"),
                ),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Users.userinfo",
                        verbose_name=" خریدار",
                    ),
                ),
            ],
            options={
                "verbose_name": "سبدخرید",
                "verbose_name_plural": "سبدخرید",
            },
        ),
        migrations.CreateModel(
            name="CartProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(default=uuid.uuid4, max_length=500)),
                (
                    "RCP",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="کد مرسوله"
                    ),
                ),
                (
                    "Quantity",
                    models.IntegerField(default=1, verbose_name="تعداد محصول"),
                ),
                ("Amount", models.IntegerField(default=0, verbose_name="مبلغ سفارش")),
                ("Fee", models.IntegerField(default=0, verbose_name="فی")),
                (
                    "discount",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="مقدار تخفیف"
                    ),
                ),
                (
                    "Offless",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="قیمت بدون تخفیف"
                    ),
                ),
                (
                    "Tax",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="مالیات بر ارزش افزوده",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Created"),
                            (1, "Accepted"),
                            (2, "Declined"),
                            (3, "Exchanged"),
                            (4, "Discarded"),
                            (5, "Exchangeproccess"),
                        ],
                        default=0,
                        verbose_name="وضعیت سبد خرید",
                    ),
                ),
                (
                    "Created_At",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="تاریخ اضافه شدن به سبد",
                    ),
                ),
                ("Vouchered", models.BooleanField(default=False, verbose_name="کوپن")),
                ("weight", models.IntegerField(default=0, verbose_name="وزن کل")),
                (
                    "Barcode",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=Warehouse.models.CartFiles,
                        verbose_name="تصویر بارکد",
                    ),
                ),
                ("Active", models.BooleanField(default=True, verbose_name="فعال")),
                ("Created", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "Cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cartproduct_cart",
                        to="Warehouse.cart",
                        verbose_name="سبدخرید",
                    ),
                ),
                (
                    "Variety",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="size_cart",
                        to="Products.varietysub",
                        verbose_name="تنوع محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "CartProduct",
                "verbose_name_plural": "CartProducts",
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Code",
                    models.CharField(
                        default=Warehouse.models.get_random_string,
                        max_length=6,
                        verbose_name="کوپن تخفیف",
                    ),
                ),
                (
                    "Type",
                    models.CharField(
                        choices=[("1", "دسته بندی"), ("2", "فاکتور")],
                        default="2",
                        max_length=50,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "Discount",
                    Products.models.IntegerRangeField(
                        default=0, verbose_name="درصد تخفیف"
                    ),
                ),
                (
                    "MaxPrice",
                    models.PositiveIntegerField(default=0, verbose_name="حداکثر تخفیف"),
                ),
                (
                    "MaxUse",
                    models.PositiveIntegerField(
                        default=1, verbose_name="حداکثر استفاده کاربر"
                    ),
                ),
                (
                    "Time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="زمان"
                    ),
                ),
                ("Active", models.BooleanField(default=True, verbose_name="فعال")),
                ("Created", models.DateTimeField(auto_now_add=True)),
                ("Modified", models.DateTimeField(auto_now=True)),
                (
                    "Category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_cat",
                        to="Products.category",
                        verbose_name="دسته بندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "کوپن تخفیف",
                "verbose_name_plural": "کوپن تخفیف",
            },
        ),
        migrations.CreateModel(
            name="FortunePrize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "RFP",
                    models.CharField(
                        blank=True,
                        default=Warehouse.models.get_random_string,
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "Title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="عنوان"
                    ),
                ),
                ("Price", models.PositiveIntegerField(default=0, verbose_name="مبلغ")),
                ("Null", models.BooleanField(default=False, verbose_name="پوچ")),
                ("Created_At", models.DateTimeField(auto_now_add=True)),
                ("Modified_At", models.DateTimeField(auto_now=True)),
                ("Active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "Coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fortune_coupon",
                        to="Warehouse.coupon",
                        verbose_name="کوپن",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WheelOfFortune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="زمان"
                    ),
                ),
                (
                    "MaxUse",
                    models.PositiveIntegerField(
                        default=1, verbose_name="حداکثر استفاده کاربر"
                    ),
                ),
                ("Created_At", models.DateTimeField(auto_now_add=True)),
                ("Modified_At", models.DateTimeField(auto_now=True)),
                ("Active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name_plural": "گردونه شانس",
            },
        ),
        migrations.CreateModel(
            name="WishList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(default=uuid.uuid4, max_length=500)),
                (
                    "RW",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="کد آیتم مورد علاقه",
                    ),
                ),
                ("Created", models.DateTimeField(auto_now_add=True)),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Users.userinfo",
                        verbose_name=" خریدار",
                    ),
                ),
                (
                    "Variety",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Products.varietysub",
                        verbose_name="تنوع محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "مورد علاقه ها",
                "verbose_name_plural": "مورد علاقه ها",
            },
        ),
        migrations.CreateModel(
            name="Shipping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=250, verbose_name="نام")),
                ("Phone", models.CharField(max_length=12, verbose_name="شماره تماس")),
                ("Address", models.TextField(verbose_name="آدرس")),
                ("PostalCode", models.CharField(max_length=10, verbose_name="کد پستی")),
                ("No", models.CharField(max_length=4, verbose_name="پلاک")),
                (
                    "Unit",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="واحد"
                    ),
                ),
                (
                    "Type",
                    models.IntegerField(
                        choices=[(0, "پیک موتوری"), (1, "پست")],
                        default=1,
                        verbose_name="شیوه ارسال",
                    ),
                ),
                (
                    "Tips",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "TrackNumber",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="کد رهگیری پستی",
                    ),
                ),
                ("Created", models.DateTimeField(auto_now_add=True)),
                ("Modified", models.DateTimeField(auto_now=True)),
                (
                    "Cart",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_cart",
                        to="Warehouse.cart",
                        verbose_name="ادرس خریدار",
                    ),
                ),
                (
                    "City",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="City",
                        to="Main.city",
                        verbose_name="شهر",
                    ),
                ),
                (
                    "State",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="State",
                        to="Main.city",
                        verbose_name="استان",
                    ),
                ),
            ],
            options={
                "verbose_name": "مشخصات ارسال",
                "verbose_name_plural": "مشخصات ارسال",
            },
        ),
        migrations.CreateModel(
            name="PurchaseTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Phone", models.CharField(max_length=11, verbose_name="شماره تماس")),
                (
                    "Describtion",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "Report",
                    models.TextField(blank=True, null=True, verbose_name="گزارش"),
                ),
                (
                    "Status",
                    models.CharField(
                        choices=[
                            ("1", "جدید"),
                            ("2", "در حال پردازش"),
                            ("3", "انجام شده"),
                        ],
                        default="1",
                        max_length=50,
                        verbose_name="وضعیت",
                    ),
                ),
                ("Created_At", models.DateTimeField(auto_now_add=True)),
                ("Modified_At", models.DateTimeField(auto_now=True)),
                (
                    "Cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="track_cart",
                        to="Warehouse.cart",
                        verbose_name="سبدخرید",
                    ),
                ),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Users.userinfo",
                        verbose_name=" خریدار",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "پیگیری سفارش",
            },
        ),
        migrations.CreateModel(
            name="FortuneUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Usage",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد استفاده کاربر"
                    ),
                ),
                ("Created", models.DateTimeField(auto_now_add=True)),
                (
                    "Prize",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_prize",
                        to="Warehouse.fortuneprize",
                        verbose_name="جایزه",
                    ),
                ),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Users.userinfo",
                        verbose_name=" خریدار",
                    ),
                ),
                (
                    "Wheel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_wheel",
                        to="Warehouse.wheeloffortune",
                        verbose_name="گردونه",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "برندگان گردونه",
            },
        ),
        migrations.AddField(
            model_name="fortuneprize",
            name="Wheel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prize_wheel",
                to="Warehouse.wheeloffortune",
                verbose_name="گردونه",
            ),
        ),
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "RCE",
                    models.CharField(
                        default=Warehouse.models.get_random_string, max_length=50
                    ),
                ),
                (
                    "Status",
                    models.CharField(
                        choices=[
                            ("1", "جدید"),
                            ("4", "در انتظار دریافت"),
                            ("2", "درحال انجام"),
                            ("3", "پردازش پرداخت"),
                            ("4", "انجام شده"),
                        ],
                        default="1",
                        max_length=50,
                        verbose_name="وضعیت",
                    ),
                ),
                ("Report", models.TextField(verbose_name="گزارش")),
                ("Active", models.BooleanField(default=True, verbose_name="فعال")),
                ("Created", models.DateTimeField(auto_now_add=True)),
                ("Modified", models.DateTimeField(auto_now=True)),
                (
                    "CP",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oldcart_exchange",
                        to="Warehouse.cartproduct",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "NewCP",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newcart_exchange",
                        to="Warehouse.cartproduct",
                        verbose_name="سفارش جدید",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "تعویض محصول",
            },
        ),
        migrations.CreateModel(
            name="CouponUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Usage",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد استفاده کاربر"
                    ),
                ),
                ("Amount", models.PositiveIntegerField(default=0, verbose_name="مبلغ")),
                ("Created", models.DateTimeField(auto_now_add=True)),
                (
                    "Coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_coupon",
                        to="Warehouse.coupon",
                        verbose_name="کوپن",
                    ),
                ),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Users.userinfo",
                        verbose_name=" خریدار",
                    ),
                ),
            ],
            options={
                "verbose_name": "CouponUser",
                "verbose_name_plural": "CouponUsers",
            },
        ),
        migrations.CreateModel(
            name="CartPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Slug", models.SlugField(default=uuid.uuid4, max_length=500)),
                ("Auth", models.CharField(max_length=500)),
                ("Amount", models.IntegerField(default=0)),
                ("Ref", models.CharField(blank=True, max_length=100, null=True)),
                ("Status", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "DigitalReceipt",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "Portal",
                    models.IntegerField(
                        choices=[(1, "Sepehrpay"), (2, "Zarinpal")],
                        default=2,
                        verbose_name="درگاه",
                    ),
                ),
                ("Verified", models.BooleanField(default=False)),
                ("Response", models.CharField(max_length=400)),
                (
                    "Cart",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_cart",
                        to="Warehouse.cart",
                        verbose_name="سبد خرید",
                    ),
                ),
            ],
        ),
    ]
