# Generated by Django 4.2.7 on 2023-11-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartproduct",
            name="Amount",
            field=models.BigIntegerField(default=0, verbose_name="مبلغ سفارش"),
        ),
        migrations.AlterField(
            model_name="cartproduct",
            name="Fee",
            field=models.BigIntegerField(default=0, verbose_name="فی"),
        ),
    ]
