# Generated by Django 4.2.7 on 2023-11-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Warehouse", "0003_remove_cart_tax_remove_cartproduct_tax"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="Amount",
            field=models.BigIntegerField(default=0, verbose_name="مبلغ کل سفارشات"),
        ),
        migrations.AlterField(
            model_name="cart",
            name="TotalDiscount",
            field=models.BigIntegerField(
                blank=True, default=0, null=True, verbose_name="مجموع تخفیف"
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="TotalPrice",
            field=models.BigIntegerField(default=0, verbose_name="مبلغ کل سبد خرید"),
        ),
        migrations.AlterField(
            model_name="cartproduct",
            name="Offless",
            field=models.BigIntegerField(
                blank=True, default=0, null=True, verbose_name="قیمت بدون تخفیف"
            ),
        ),
        migrations.AlterField(
            model_name="cartproduct",
            name="discount",
            field=models.BigIntegerField(
                blank=True, default=0, null=True, verbose_name="مقدار تخفیف"
            ),
        ),
    ]
