# Generated by Django 4.2.7 on 2023-11-04 19:20

import Blog.models
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Slug", models.SlugField(default=uuid.uuid4, max_length=500)),
                ("Title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "Text",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                ("Demo", models.TextField(blank=True, null=True)),
                ("Poster", models.ImageField(blank=True, null=True, upload_to="Blog/")),
                (
                    "MetaKeyWords",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "MetaDescription",
                    models.CharField(blank=True, max_length=360, null=True),
                ),
                ("MetaTitle", models.CharField(blank=True, max_length=50, null=True)),
                ("Rate", models.IntegerField(default=0, verbose_name="امتیاز")),
                ("Created_At", models.DateTimeField(auto_now_add=True)),
                (
                    "Created",
                    models.CharField(
                        blank=True,
                        default=Blog.models.JDATE,
                        max_length=50,
                        null=True,
                        verbose_name="تاریخ ثبت",
                    ),
                ),
                ("Modified_At", models.DateTimeField(auto_now=True)),
                ("Active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name_plural": "پست ها",
            },
        ),
        migrations.CreateModel(
            name="PostTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Value", models.CharField(max_length=50, verbose_name="کلمه")),
                (
                    "ClickCount",
                    models.IntegerField(default=0, verbose_name="تعداد کلیک برچسب"),
                ),
                (
                    "Usage",
                    models.IntegerField(default=1, verbose_name="تعداد استفاده از تگ"),
                ),
                ("Active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "Post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_post",
                        to="Blog.post",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "تگ های پست",
            },
        ),
        migrations.CreateModel(
            name="PostRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IP", models.CharField(blank=True, max_length=15, null=True)),
                ("Active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "Post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_post",
                        to="Blog.post",
                    ),
                ),
                (
                    "User",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Users.userinfo",
                        verbose_name="کاربر",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Phone", models.CharField(max_length=11)),
                ("Name", models.CharField(max_length=100)),
                ("Text", models.TextField(blank=True, max_length=500, null=True)),
                ("Rate", models.IntegerField(default=0, verbose_name="امتیاز")),
                ("Created_At", models.DateTimeField(auto_now_add=True)),
                (
                    "Created",
                    models.CharField(
                        blank=True,
                        default=Blog.models.JDATE,
                        max_length=50,
                        null=True,
                        verbose_name="تاریخ ثبت",
                    ),
                ),
                ("Modified_At", models.DateTimeField(auto_now=True)),
                ("Active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "Post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_post",
                        to="Blog.post",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "کامنت های پست",
            },
        ),
    ]
