# Generated by Django 4.2.7 on 2023-12-11 19:18

import Blog.models
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0002_post_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="Slug",
        ),
        migrations.AddField(
            model_name="post",
            name="RPO",
            field=models.CharField(
                default=Blog.models.get_random_string,
                max_length=50,
                verbose_name="شماره پست",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="Author",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="نویسنده"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="Demo",
            field=models.TextField(blank=True, null=True, verbose_name="دمو"),
        ),
        migrations.AlterField(
            model_name="post",
            name="Poster",
            field=models.ImageField(
                blank=True, null=True, upload_to="Blog/", verbose_name="پوستر"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="Text",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="متن"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="Title",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="عنوان"
            ),
        ),
    ]
