# Generated by Django 4.2.7 on 2023-11-04 19:20

import Main.models
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("parent", models.IntegerField(default=0)),
                ("title", models.CharField(max_length=100)),
                ("Active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
            },
        ),
        migrations.CreateModel(
            name="CodeReg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Code",
                    models.CharField(
                        default=Main.models.Generate, max_length=6, verbose_name="کد"
                    ),
                ),
                ("Phone", models.CharField(max_length=50, verbose_name="شماره همراه")),
                ("Email", models.CharField(max_length=50, verbose_name="ایمیل")),
                ("Active", models.BooleanField(default=True, verbose_name="وضعیت")),
                (
                    "Created_At",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ ایجاد"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "CodeRegs",
            },
        ),
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100, verbose_name="نام")),
                ("Email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                ("Phone", models.CharField(max_length=13, verbose_name="تلفن همراه")),
                ("Text", models.TextField(max_length=500, verbose_name="متن")),
                ("Subject", models.CharField(max_length=50, verbose_name="موضوع")),
                (
                    "Created",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ"),
                ),
            ],
            options={
                "verbose_name": "تماس باما",
                "verbose_name_plural": "تماس باما",
            },
        ),
        migrations.CreateModel(
            name="MiniBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="MiniBox/",
                        verbose_name="تصویر",
                    ),
                ),
                ("Text", models.CharField(max_length=200, verbose_name="متن")),
                ("Url", models.URLField(max_length=250, verbose_name="لینک")),
            ],
            options={
                "verbose_name": "باکس لیست تخفیف",
                "verbose_name_plural": "باکس لیست تخفیف",
            },
        ),
        migrations.CreateModel(
            name="Shortener",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Real", models.CharField(max_length=400, verbose_name="مسیر اصلی")),
                (
                    "Short",
                    models.URLField(blank=True, null=True, verbose_name="لینک کوتاه"),
                ),
            ],
            options={
                "verbose_name": "Shortener",
                "verbose_name_plural": "Shorteners",
            },
        ),
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "RS",
                    models.CharField(
                        blank=True,
                        default=Main.models.get_random_string,
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "Type",
                    models.CharField(
                        choices=[
                            ("0", "گردونه شانس"),
                            ("1", "تصویر"),
                            ("2", "مستقل"),
                            ("3", "تصویر با لینک"),
                        ],
                        default="1",
                        max_length=50,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "Image_H",
                    models.ImageField(upload_to="Slider/", verbose_name="تصویر افقی"),
                ),
                (
                    "Image_V",
                    models.ImageField(upload_to="Slider/", verbose_name="تصویر عمودی"),
                ),
                (
                    "Url",
                    models.URLField(
                        blank=True, max_length=250, null=True, verbose_name="لینک"
                    ),
                ),
                (
                    "Rich",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                (
                    "Order",
                    models.PositiveIntegerField(default=0, verbose_name="اولویت"),
                ),
                (
                    "Created",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ"),
                ),
            ],
            options={
                "verbose_name": "اسلایدر",
                "verbose_name_plural": "اسلایدر",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("Email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                ("Phone", models.CharField(max_length=13, verbose_name="شماره تماس")),
                (
                    "Gender",
                    models.IntegerField(
                        choices=[(1, "Male"), (2, "Female")],
                        default=2,
                        verbose_name="جنسیت",
                    ),
                ),
                (
                    "Password",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="رمز عبور"
                    ),
                ),
                ("key", models.BinaryField(blank=True, max_length=200, null=True)),
                ("Name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "Position",
                    models.CharField(
                        choices=[
                            ("0", "ابر یوزر"),
                            ("1", "ادمین"),
                            ("2", "تولید کننده محتوا"),
                            ("3", "انباردار"),
                            ("4", "حسابدار"),
                            ("5", "سئوکار"),
                        ],
                        default="1",
                        max_length=50,
                        verbose_name="موقعیت شغلی",
                    ),
                ),
                ("Created_At", models.DateTimeField(auto_now_add=True)),
                ("Modified_At", models.DateTimeField(auto_now=True)),
                ("Last_Login", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "پرسنل",
            },
        ),
        migrations.CreateModel(
            name="TwinBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Image",
                    models.ImageField(upload_to="TwinBox/", verbose_name="تصویر"),
                ),
                (
                    "Order",
                    models.PositiveIntegerField(default=0, verbose_name="اولویت"),
                ),
                ("Url", models.URLField(max_length=250, verbose_name="لینک")),
            ],
            options={
                "verbose_name": "باکس های دوقلو",
                "verbose_name_plural": "باکس های دوقلو",
            },
        ),
        migrations.CreateModel(
            name="QuickOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="QuickOffer/",
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "Url",
                    models.URLField(
                        blank=True, max_length=250, null=True, verbose_name="لینک"
                    ),
                ),
                (
                    "Name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="نام"
                    ),
                ),
                (
                    "Created",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ"),
                ),
                ("Active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "Variety",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Products.varietysub",
                        verbose_name="تنوع محصول",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "آفر های سریع",
            },
        ),
        migrations.CreateModel(
            name="OfferBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="زمان"
                    ),
                ),
                ("Text", models.CharField(max_length=200, verbose_name="متن")),
                (
                    "Image",
                    models.ImageField(upload_to="OfferBox/", verbose_name="تصویر"),
                ),
                (
                    "Variety",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Products.varietysub",
                        verbose_name="تنوع محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "باکس پیشنهاد ویزه",
                "verbose_name_plural": "باکس پیشنهاد ویزه",
            },
        ),
        migrations.CreateModel(
            name="DiscountBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="زمان"
                    ),
                ),
                ("Text", models.CharField(max_length=200, verbose_name="متن")),
                (
                    "Image",
                    models.ImageField(upload_to="DiscountBox/", verbose_name="تصویر"),
                ),
                (
                    "Variety",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Products.varietysub",
                        verbose_name="تنوع محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "باکس تخفیف ویژه",
                "verbose_name_plural": "باکس تخفیف ویژه",
            },
        ),
        migrations.CreateModel(
            name="BigSellBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Image",
                    models.ImageField(upload_to="BigSellBox/", verbose_name="تصویر"),
                ),
                ("Text", models.CharField(max_length=200, verbose_name="متن")),
                ("Url", models.URLField(max_length=250, verbose_name="لینک")),
                (
                    "Variety",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Products.varietysub",
                        verbose_name="تنوع محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "باکس بزرگ",
                "verbose_name_plural": "باکس بزرگ",
            },
        ),
    ]
