# Generated by Django 4.2.7 on 2023-11-21 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=100)),
                ("FirstName", models.CharField(max_length=100)),
                ("LastName", models.CharField(max_length=100)),
                ("NationalId", models.CharField(max_length=10)),
                ("Phone", models.CharField(max_length=11)),
                ("PostalAddress", models.CharField(max_length=500)),
                ("PostalCode", models.CharField(max_length=10)),
                ("Number", models.CharField(max_length=4)),
                ("Unit", models.CharField(blank=True, max_length=5)),
                ("Active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "City",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="city_city",
                        to="Main.city",
                        verbose_name="شهر",
                    ),
                ),
                (
                    "State",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_city",
                        to="Main.city",
                        verbose_name="استان",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "آدرس",
            },
        ),
    ]
