# Generated by Django 4.2.7 on 2023-11-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0002_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="FirstName",
        ),
        migrations.RemoveField(
            model_name="address",
            name="LastName",
        ),
        migrations.RemoveField(
            model_name="address",
            name="NationalId",
        ),
        migrations.AddField(
            model_name="address",
            name="Name",
            field=models.CharField(default=0, max_length=100, verbose_name="نام"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="Number",
            field=models.CharField(max_length=4, verbose_name="پلاک"),
        ),
        migrations.AlterField(
            model_name="address",
            name="Phone",
            field=models.CharField(max_length=11, verbose_name="شماره همراه"),
        ),
        migrations.AlterField(
            model_name="address",
            name="PostalAddress",
            field=models.CharField(max_length=500, verbose_name="آدرس پستی"),
        ),
        migrations.AlterField(
            model_name="address",
            name="PostalCode",
            field=models.CharField(max_length=10, verbose_name="کد پستی"),
        ),
        migrations.AlterField(
            model_name="address",
            name="Title",
            field=models.CharField(max_length=100, verbose_name="عنوان آدرس"),
        ),
        migrations.AlterField(
            model_name="address",
            name="Unit",
            field=models.CharField(blank=True, max_length=5, verbose_name="واحد"),
        ),
    ]
