# Generated by Django 4.2.7 on 2023-11-26 16:18

import Main.models
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Products", "0008_alter_varietysub_reserevedquantity"),
        ("Main", "0004_address_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "RS",
                    models.CharField(
                        blank=True,
                        default=Main.models.get_random_string,
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "Type",
                    models.CharField(
                        choices=[
                            ("1", "تصویر"),
                            ("2", "مستقل"),
                            ("3", "تصویر با لینک"),
                        ],
                        default="1",
                        max_length=50,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "Placement",
                    models.CharField(
                        choices=[
                            ("1", "اسلایدر"),
                            ("2", "باکس میانی"),
                            ("3", "باکس سه گانه"),
                        ],
                        default="1",
                        max_length=50,
                        verbose_name="جایگاه",
                    ),
                ),
                (
                    "Image_H",
                    models.ImageField(upload_to="Slider/", verbose_name="تصویر افقی"),
                ),
                (
                    "Image_V",
                    models.ImageField(upload_to="Slider/", verbose_name="تصویر عمودی"),
                ),
                (
                    "Url",
                    models.URLField(
                        blank=True, max_length=250, null=True, verbose_name="لینک"
                    ),
                ),
                (
                    "Rich",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                (
                    "Order",
                    models.PositiveIntegerField(default=0, verbose_name="اولویت"),
                ),
                (
                    "Created",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ"),
                ),
            ],
            options={
                "verbose_name": "اسلایدر",
                "verbose_name_plural": "اسلایدر",
            },
        ),
        migrations.CreateModel(
            name="Offers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="QuickOffer/",
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "Url",
                    models.URLField(
                        blank=True, max_length=250, null=True, verbose_name="لینک"
                    ),
                ),
                (
                    "Created",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ"),
                ),
                ("Active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "Product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Products.product",
                        verbose_name="تنوع محصول",
                    ),
                ),
                (
                    "Sub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Products.varietysub",
                        verbose_name="تنوع محصول",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "آفر ها",
            },
        ),
        migrations.RemoveField(
            model_name="bigsellbox",
            name="Variety",
        ),
        migrations.RemoveField(
            model_name="discountbox",
            name="Variety",
        ),
        migrations.DeleteModel(
            name="MiniBox",
        ),
        migrations.RemoveField(
            model_name="offerbox",
            name="Variety",
        ),
        migrations.RemoveField(
            model_name="quickoffer",
            name="Variety",
        ),
        migrations.DeleteModel(
            name="Shortener",
        ),
        migrations.DeleteModel(
            name="Slider",
        ),
        migrations.DeleteModel(
            name="TwinBox",
        ),
        migrations.DeleteModel(
            name="BigSellBox",
        ),
        migrations.DeleteModel(
            name="DiscountBox",
        ),
        migrations.DeleteModel(
            name="OfferBox",
        ),
        migrations.DeleteModel(
            name="QuickOffer",
        ),
    ]
