# Generated by Django 4.2.7 on 2023-11-26 16:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0005_imagebox_offers_remove_bigsellbox_variety_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagebox",
            options={"verbose_name_plural": "باکس تصاویر"},
        ),
    ]
