# Generated by Django 4.2.7 on 2023-11-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0006_alter_imagebox_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagebox",
            name="Active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
    ]
