# Generated by Django 4.2.7 on 2023-11-26 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Products", "0008_alter_varietysub_reserevedquantity"),
        ("Main", "0007_imagebox_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="offers",
            name="Type",
            field=models.CharField(
                choices=[("1", "پاپ اپ"), ("2", "تخفبف"), ("3", "انتخابی")],
                default="1",
                max_length=50,
                verbose_name="نوع",
            ),
        ),
        migrations.AlterField(
            model_name="offers",
            name="Product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Products.product",
                verbose_name="تنوع محصول",
            ),
        ),
    ]
