# Generated by Django 4.2.7 on 2023-11-26 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0008_offers_type_alter_offers_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offers",
            name="Image",
        ),
        migrations.RemoveField(
            model_name="offers",
            name="Url",
        ),
    ]
