# Generated by Django 4.2.7 on 2023-11-26 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Products", "0008_alter_varietysub_reserevedquantity"),
        ("Main", "0009_remove_offers_image_remove_offers_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offers",
            name="Product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Products.product",
                verbose_name="محصول",
            ),
        ),
    ]
