# Generated by Django 4.2.7 on 2023-11-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Products", "0002_product_demo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="BasePrice",
            field=models.BigIntegerField(default=0, verbose_name="قیمت پایه"),
        ),
        migrations.AlterField(
            model_name="varietysub",
            name="FinalPrice",
            field=models.BigIntegerField(default=0, verbose_name="قیمت نهایی"),
        ),
    ]
