# Generated by Django 4.2.7 on 2023-11-08 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Products", "0003_alter_product_baseprice_alter_varietysub_finalprice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="guarantee",
            options={"verbose_name_plural": "گارانتی"},
        ),
        migrations.RemoveField(
            model_name="filters",
            name="Type",
        ),
        migrations.CreateModel(
            name="FilterValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "Filter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="val_filter",
                        to="Products.filters",
                        verbose_name="فیلتر",
                    ),
                ),
            ],
            options={
                "verbose_name": "FilterValue",
                "verbose_name_plural": "FilterValues",
            },
        ),
    ]
