# Generated by Django 4.2.7 on 2023-11-12 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Products", "0005_productfilter"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="ColorName",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="نام رنگ"
            ),
        ),
        migrations.AlterField(
            model_name="productcomment",
            name="Product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cm_prd",
                to="Products.product",
                verbose_name="محصول",
            ),
        ),
    ]
