# Generated by Django 4.2.7 on 2023-11-12 19:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Products", "0006_productimage_colorname_alter_productcomment_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="ColorName",
        ),
    ]
