# Generated by Django 4.2.7 on 2023-11-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Products", "0007_remove_productimage_colorname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="varietysub",
            name="ReserevedQuantity",
            field=models.PositiveIntegerField(
                blank=True, default=0, verbose_name=" موجودی رزرو"
            ),
        ),
    ]
